runtime: python311

entrypoint: gunicorn -b :$PORT app:app

handlers:
- url: /.*
  script: auto

env_variables:
  FLASK_ENV: 'production'
  SECRET_KEY: 'your-secret-key'
  DATABASE_URL: 'your-database-url'
